"use client";

import { useState } from "react";
import Link from "next/link";
import {
  BarChart3,
  BookOpen,
  CalendarDays,
  Check,
  ChevronDown,
  ClipboardCheck,
  FileText,
  Flag,
  Home,
  LogOut,
  Menu,
  Plus,
  Search,
  Settings2,
  ShieldCheck,
  Sparkles,
  Target,
  X,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";

const nav = [
  { label: "Översikt", href: "/", icon: Home },
  { label: "Årshjul", href: "/year-wheel", icon: CalendarDays },
  { label: "Manual", href: "/manual", icon: BookOpen },
  { label: "Avvikelser", href: "/deviations", icon: Flag, badge: "3" },
];

function Brand() {
  return <Link href="/" className="flex items-center gap-3"><span className="brand-mark">Q</span><span className="font-semibold tracking-tight">quality works <span className="text-primary">light</span></span></Link>;
}

function Shell({ children, title, eyebrow = "KVALITETSLEDNING" }: { children: React.ReactNode; title: string; eyebrow?: string }) {
  const [open, setOpen] = useState(false);
  return <div className="min-h-screen bg-background text-foreground"><aside className={`app-sidebar ${open ? "is-open" : ""}`}><div className="flex items-center justify-between p-5"><Brand /><button className="md:hidden" onClick={() => setOpen(false)} aria-label="Stäng meny"><X /></button></div><div className="px-5 py-6"><p className="eyebrow">Arbetsyta</p><div className="mt-3 flex items-center gap-3 rounded-xl border bg-card p-3"><div className="avatar">AB</div><div><p className="text-sm font-semibold">Alfa Bygg AB</p><p className="text-xs text-muted-foreground">Huvudkontor</p></div><ChevronDown className="ml-auto size-4 text-muted-foreground" /></div></div><nav className="flex flex-col gap-1 px-3">{nav.map((item) => { const Icon = item.icon; return <Link key={item.href} href={item.href} className="nav-link"><Icon className="size-4" /><span>{item.label}</span>{item.badge && <span className="ml-auto nav-badge">{item.badge}</span>}</Link>; })}</nav><div className="mt-auto px-3 pb-5"><Link href="/manual" className="nav-link"><Settings2 className="size-4" />Inställningar</Link><Link href="/login" className="nav-link"><LogOut className="size-4" />Logga ut</Link></div></aside><div className="app-main"><header className="app-header"><button className="md:hidden" onClick={() => setOpen(true)} aria-label="Öppna meny"><Menu /></button><div className="flex items-center gap-3"><span className="hidden text-sm text-muted-foreground sm:inline">Alfa Bygg AB</span><span className="header-divider" /><span className="text-sm font-medium">Kvalitetsledning</span></div><div className="flex items-center gap-3"><button className="icon-button" aria-label="Sök"><Search className="size-4" /></button><div className="avatar avatar-small">AB</div></div></header><main className="mx-auto w-full max-w-7xl px-5 py-8 md:px-10"><div className="mb-8"><p className="eyebrow text-primary">{eyebrow}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight md:text-4xl">{title}</h1></div>{children}</main></div></div>;
}

export function LoginPage() { return <div className="login-page"><div className="login-brand"><Brand /></div><Card className="login-card"><CardHeader><div className="brand-mark mb-5">Q</div><CardTitle className="text-2xl">Välkommen tillbaka</CardTitle><p className="text-sm text-muted-foreground">Logga in för att fortsätta till din kvalitetsledning.</p></CardHeader><CardContent><div className="flex flex-col gap-4"><label className="field-label">E-postadress<Input type="email" placeholder="namn@foretag.se" /></label><label className="field-label">Lösenord<Input type="password" placeholder="••••••••" /></label><div className="flex justify-end"><Button variant="link" className="h-auto p-0 text-xs">Glömt lösenord?</Button></div><Button className="mt-2 w-full" asChild><Link href="/">Logga in <span aria-hidden>→</span></Link></Button></div><div className="my-6 flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border" />eller<span className="h-px flex-1 bg-border" /></div><Button variant="outline" className="w-full">Fortsätt med BankID</Button></CardContent></Card><p className="login-footer">© 2026 Quality Works · Hjälp & support</p></div> }

export function DashboardPage() { return <Shell title="God morgon, Anna"><div className="grid gap-5 lg:grid-cols-[1.5fr_1fr]"><Card className="hero-card"><CardContent className="flex h-full flex-col justify-between p-7"><div><Badge className="mb-6">Bra jobbat</Badge><h2 className="max-w-lg text-2xl font-semibold">Du har koll på läget.</h2><p className="mt-3 max-w-lg leading-6 text-muted-foreground">Fortsätt arbeta strukturerat med kvalitet. Här ser du en snabb överblick över vad som händer i din verksamhet.</p></div><Button className="mt-10 w-fit" asChild><Link href="/year-wheel">Visa mitt årshjul <span aria-hidden>→</span></Link></Button></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center justify-between text-base">Att göra <Badge variant="secondary">3 kvar</Badge></CardTitle></CardHeader><CardContent className="flex flex-col gap-3">{["Bekräfta ledningens genomgång", "Uppdatera arbetsmanualen", "Följ upp öppen avvikelse"].map((task) => <div className="task-row" key={task}><span className="check-circle"><Check className="size-3" /></span><span className="text-sm">{task}</span></div>)}</CardContent></Card></div><div className="mt-5 grid gap-5 md:grid-cols-3"><StatCard icon={Target} label="Kvalitetsmål" value="84%" detail="+8% sedan förra månaden" /><StatCard icon={ClipboardCheck} label="Pågående aktiviteter" value="7" detail="2 behöver din uppmärksamhet" /><StatCard icon={ShieldCheck} label="Senaste revision" value="Godkänd" detail="14 maj 2026" /></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Senaste händelser</CardTitle></CardHeader><CardContent className="flex flex-col gap-4">{["Ledningens genomgång publicerades", "Ny aktivitet lades till i årshjulet", "Avvikelse #1048 markerades som klar"].map((event, i) => <div className="event-row" key={event}><span className="event-dot" /><div><p className="text-sm font-medium">{event}</p><p className="text-xs text-muted-foreground">{i + 1} dagar sedan</p></div></div>)}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Kvalitetsarbete över tid</CardTitle></CardHeader><CardContent><div className="chart-placeholder"><BarChart3 className="size-7 text-primary" /><div className="chart-bars"><i /><i /><i /><i /><i /><i /><i /></div></div><div className="mt-3 flex justify-between text-xs text-muted-foreground"><span>Jan</span><span>Apr</span><span>Jul</span><span>Okt</span></div></CardContent></Card></div></Shell> }

function StatCard({ icon: Icon, label, value, detail }: { icon: typeof Target; label: string; value: string; detail: string }) { return <Card><CardContent className="p-5"><div className="flex items-start justify-between"><span className="icon-tile"><Icon className="size-4" /></span><span className="text-xs text-success">↑</span></div><p className="mt-5 text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p><p className="mt-2 text-xs text-muted-foreground">{detail}</p></CardContent></Card> }

export function ManualPage() { const [published, setPublished] = useState(false); return <Shell title="Arbetsmanual" eyebrow="MANUAL"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><p className="max-w-xl text-sm leading-6 text-muted-foreground">Samla arbetssätt, ansvar och rutiner på ett ställe. Gör kvalitet lätt att göra rätt.</p><div className="flex gap-2"><Button variant="outline"><FileText />Förhandsvisa</Button><Button onClick={() => setPublished(true)}><Check />{published ? "Publicerad" : "Publicera"}</Button></div></div><div className="tabs-row"><span className="tab-active">Arbetsmanual</span><span>Original</span><span>Versionshistorik</span></div><div className="mt-5 grid gap-5 lg:grid-cols-[280px_1fr]"><Card><CardHeader><CardTitle className="text-sm">Innehåll</CardTitle></CardHeader><CardContent className="flex flex-col gap-1 p-3 pt-0">{["Grundinställningar", "Vårt arbetssätt", "Ansvar och roller", "Rutiner", "Bilagor"].map((item, i) => <button className={`manual-nav ${i === 0 ? "active" : ""}`} key={item}>{item}{i === 0 && <span>›</span>}</button>)}</CardContent></Card><Card><CardHeader><Badge className="w-fit">1 av 5</Badge><CardTitle className="mt-3 text-xl">Grundinställningar</CardTitle><p className="text-sm text-muted-foreground">Börja här. Dessa uppgifter används i hela er kvalitetsledning.</p></CardHeader><CardContent><div className="grid gap-5 sm:grid-cols-2"><label className="field-label">Företagsnamn<Input defaultValue="Alfa Bygg AB" /></label><label className="field-label">Organisationsnummer<Input defaultValue="559123-4567" /></label><label className="field-label">Kvalitetsansvarig<Input defaultValue="Anna Berg" /></label><label className="field-label">Giltig från<Input type="date" defaultValue="2026-01-01" /></label></div><label className="field-label mt-5">Om verksamheten<Textarea defaultValue="Vi på Alfa Bygg arbetar för att leverera byggtjänster med hög och jämn kvalitet." /></label><div className="mt-6 flex justify-end"><Button>Spara ändringar <span aria-hidden>→</span></Button></div></CardContent></Card></div></Shell> }

export function DeviationsPage() { return <Shell title="Avvikelser" eyebrow="KVALITETSARBETE"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-muted-foreground">Fånga upp, hantera och lär av det som inte blev som planerat.</p><Button><Plus />Ny avvikelse</Button></div><div className="mb-5 flex gap-2"><Button variant="secondary">Alla <span className="ml-1 text-xs">12</span></Button><Button variant="outline">Öppna <span className="ml-1 text-xs">3</span></Button><Button variant="outline">Klara <span className="ml-1 text-xs">9</span></Button></div><Card><CardContent className="p-0"><div className="table-scroll"><table className="data-table"><thead><tr><th>Ärende</th><th>Datum</th><th>Ansvarig</th><th>Status</th><th /></tr></thead><tbody>{[["#1048 · Material saknades vid leverans","18 juni 2026","Anna Berg","Öppen"],["#1047 · Försenad egenkontroll","12 juni 2026","Erik Lund","Pågår"],["#1046 · Felaktig märkning","04 juni 2026","Anna Berg","Klar"],["#1045 · Tillbud på arbetsplats","28 maj 2026","Johan Nilsson","Klar"]].map(([name,date,owner,status]) => <tr key={name}><td className="font-medium">{name}</td><td>{date}</td><td>{owner}</td><td><span className={`status-pill ${status === "Klar" ? "done" : status === "Pågår" ? "progress" : "open"}`}>{status}</span></td><td><button className="text-sm text-primary">Visa</button></td></tr>)}</tbody></table></div></CardContent></Card></Shell> }

export function YearWheelPage() { const months = ["Jan","Feb","Mar","Apr","Maj","Jun","Jul","Aug","Sep","Okt","Nov","Dec"]; return <Shell title="Årshjul" eyebrow="PLANERING"><div className="mb-5 flex items-center justify-between"><p className="text-sm text-muted-foreground">Planera årets återkommande kvalitetsaktiviteter.</p><Button><Plus />Lägg till aktivitet</Button></div><Card><CardContent className="p-5 md:p-8"><div className="year-wheel">{months.map((month, i) => <div key={month} className={`month month-${i + 1}`}><span>{month}</span>{[1,4,7,10].includes(i) && <i />}</div>)}<div className="wheel-center"><Sparkles className="size-5 text-primary" /><strong>2026</strong><span>Alfa Bygg</span></div></div><div className="mt-8 grid gap-3 sm:grid-cols-3"><div className="legend-item"><span className="legend-dot primary-dot" />Planerad aktivitet</div><div className="legend-item"><span className="legend-dot warning-dot" />Påminnelse</div><div className="legend-item"><span className="legend-dot success-dot" />Genomförd</div></div></CardContent></Card></Shell> }

export { Shell };
